import type { Actividad, InvitacionPendiente } from './tipos'

// Datos de prueba: el módulo de Actividades todavía no existe en el backend
// (docs/diseno-desarrollo-nucleo.md §11.2, incremento "Actividades I" en curso).
// Sustituir por la consulta real (TanStack Query) cuando el endpoint exista.

export const ACTIVIDADES_PRUEBA: Actividad[] = [
  {
    id: 'act-1',
    nombre: 'Proyecto de ecosistemas',
    objetivo: 'Investigar y presentar el impacto humano en un ecosistema local.',
    fase: 'inscripcion',
    rol: 'organizador',
    numParticipantes: 5,
    fechaClave: 'Inscripción cierra el 2 de septiembre',
    claveIngreso: 'ECO4H7KP',
    informacionGeneral:
      'Entregable final: reporte escrito de 8-10 páginas más una presentación de 10 minutos.',
    fechaInicio: '2026-08-10',
    fechaTermino: '2026-10-05',
    fechaLimiteInscripcion: '2026-09-02',
    plazoCierreDias: 10,
    numeroEquiposEsperado: 4,
  },
  {
    id: 'act-2',
    nombre: 'Taller de retroalimentación entre pares',
    objetivo: 'Practicar retroalimentación estructurada sobre entregas semanales.',
    fase: 'desarrollo',
    rol: 'organizador',
    numParticipantes: 12,
    fechaClave: 'Semana 3 de 6',
    claveIngreso: 'RETRO2XQ',
    informacionGeneral: 'Cada equipo entrega un avance semanal y recibe retroalimentación cruzada.',
    fechaInicio: '2026-07-20',
    fechaTermino: '2026-08-31',
    fechaLimiteInscripcion: '2026-07-24',
    plazoCierreDias: 7,
    numeroEquiposEsperado: 3,
  },
  {
    id: 'act-3',
    nombre: 'Curso de introducción a bases de datos',
    objetivo: 'Fundamentos de modelado relacional y SQL en equipos de práctica.',
    fase: 'archivada',
    rol: 'organizador',
    numParticipantes: 18,
    fechaClave: 'Archivada el 30 de mayo',
    claveIngreso: 'BDATOS93',
    informacionGeneral: 'Proyecto final: base de datos normalizada con consultas documentadas.',
    fechaInicio: '2026-03-02',
    fechaTermino: '2026-05-15',
    fechaLimiteInscripcion: '2026-03-06',
    plazoCierreDias: 15,
    numeroEquiposEsperado: 6,
  },
  {
    id: 'act-4',
    nombre: 'Diplomado en evaluación educativa',
    objetivo: 'Diseñar instrumentos de evaluación para trabajo colaborativo.',
    fase: 'desarrollo',
    rol: 'co-organizador',
    numParticipantes: 9,
    fechaClave: 'Semana 5 de 10',
    claveIngreso: 'DIPLO7NW',
    informacionGeneral: 'Cada equipo diseña una rúbrica y la valida con un caso real.',
    fechaInicio: '2026-06-01',
    fechaTermino: '2026-08-24',
    fechaLimiteInscripcion: '2026-06-05',
    plazoCierreDias: 10,
    numeroEquiposEsperado: 3,
  },
  {
    id: 'act-5',
    nombre: 'Debate de genética',
    objetivo: 'Argumentar posturas sobre edición genética en equipos.',
    fase: 'desarrollo',
    rol: 'participante',
    numParticipantes: 8,
    fechaClave: 'Semana 1 de 4',
    claveIngreso: 'GENET5RT',
    informacionGeneral: 'Debate formal con postura asignada por equipo y réplica cruzada.',
    fechaInicio: '2026-08-17',
    fechaTermino: '2026-09-14',
    fechaLimiteInscripcion: '2026-08-19',
    plazoCierreDias: 5,
    numeroEquiposEsperado: 4,
  },
  {
    id: 'act-6',
    nombre: 'Proyecto integrador de biología',
    objetivo: 'Producto final de investigación en equipo sobre biodiversidad.',
    fase: 'cierre',
    rol: 'participante',
    numParticipantes: 6,
    fechaClave: 'Evaluación por pares pendiente',
    claveIngreso: 'BIODIV84',
    informacionGeneral: 'Reporte de investigación con muestreo de campo documentado.',
    fechaInicio: '2026-04-06',
    fechaTermino: '2026-07-10',
    fechaLimiteInscripcion: '2026-04-10',
    plazoCierreDias: 10,
    numeroEquiposEsperado: 2,
  },
]

export const INVITACIONES_PRUEBA: InvitacionPendiente[] = [
  {
    id: 'inv-1',
    nombre: 'Club de lectura científica',
    objetivo: 'Discutir artículos de divulgación científica en equipos rotativos.',
    invitadoPor: 'Larisa Enríquez',
  },
]
